proxy-providers:
  ID:
    type: file
    path: ./proxy_provider/id.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
  MIX:
    type: file
    path: ./proxy_provider/mix.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
  DIRECTMODEM:
    type: file
    path: ./proxy_provider/directmodem.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
proxy-groups:
- name: Auto-ID_MIX
  type: fallback
  disable-udp: false
  use:
  - ID
  - MIX
  url: http://www.gstatic.com/generate_204
  interval: '100'
- name: Load-MIX_ID
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - MIX
  - ID
  url: http://www.gstatic.com/generate_204
  interval: '100'
- name: Server-UMUM
  type: select
  disable-udp: false
  proxies:
  - Load-MIX_ID
  - Auto-ID_MIX
- name: Server-INDO
  type: select
  disable-udp: false
  proxies:
  - Auto-ID_MIX
  use:
  - DIRECTMODEM
- name: Server-GAME
  type: select
  disable-udp: false
  proxies:
  - Auto-ID_MIX
  - DIRECT
  use:
  - DIRECTMODEM
- name: IKLAN
  type: select
  disable-udp: false
  proxies:
  - Server-UMUM
  - REJECT
rule-providers:
  Oisd_big:
    type: http
    behavior: classical
    path: ./rule_provider/oisd_big.yaml
    url: https://raw.githubusercontent.com/hillz2/openclash_adblock/main/oisd_big.yaml
    interval: 28800 # Update Rules Setiap 8 Jam
  Game:
    type: file
    behavior: classical
    path: ./rule_provider/game.yaml
  Umum:
    type: file
    behavior: classical
    path: ./rule_provider/umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./rule_provider/indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./rule_provider/sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./rule_provider/streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./rule_provider/bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./rule_provider/tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./rule_provider/meta.yaml
rules:
- RULE-SET,Oisd_big,IKLAN
- RULE-SET,Game,Server-GAME
- RULE-SET,indo,Server-INDO
- RULE-SET,Sosmed,Server-INDO
- RULE-SET,Streaming,Server-UMUM
- RULE-SET,Bankid,Server-INDO
- RULE-SET,Tiktok,Server-UMUM
- RULE-SET,Meta,Server-INDO
- AND,((NOT,((RULE-SET,Umum))),(NETWORK,TCP)),Server-GAME
- AND,((NOT,((RULE-SET,Umum))),(NETWORK,UDP)),Server-GAME
- MATCH,Server-UMUM
dns:
  proxy-server-nameserver:
  - 112.215.198.248
  - 112.215.198.254